---
- include: repository.yml
#Install the official nginx repository fdr supported OS's. Moved into a seperate file for readability.

- name: install nginx
  package:
    name: nginx
    state: present

- name: apply nginx config template to /etc/nginx/conf.d/mattermost.conf
  template:  
    src: mattermost.conf.j2
    dest: /etc/nginx/conf.d/mattermost.conf

- name: Allow nginx to connect to MatterMost
  command: setsebool httpd_can_network_connect true
  when: ansible_distribution == "RedHat"

- name: remove nginx default site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx