---
- hosts: all
  remote_user: root
  vars:
    mattermost_version: v1.1.0
    mattermost_user: mattermost
    db_user: mmmost
    db_name: mattermost
    db_password: notReallyPassword
    server_FQDN: www.lugnuthead.xyz
  roles:
     - common
     - postgres
     - mattermost
     - nginx
