---
- name: add key for ppa python repository
  apt_key: keyserver=keyserver.ubuntu.com id=DB82666C state=present
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")

- name: Add ppa python repository
  apt_repository: repo='deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu {{ ansible_distribution_release }} main' state=present update_cache=yes
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")

- name: ensure python2.7 latest  is installed
  apt:
    pkg: python2.7
    state: latest
    install_recommends: no
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")

- name: download code from MatterMost website
  get_url: 
    url: https://releases.mattermost.com/{{ mattermost_version }}/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz
    dest: /tmp/
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7") or (ansible_os_family == "Debian")

- name: download code from MatterMost website (using wget because get_url fails if system python is older than 2.7.5)
  command: "wget https://releases.mattermost.com/{{ mattermost_version }}/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz"
  args:        
    chdir: /tmp/
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "6")

- name: unpack mattermost archive
  unarchive: 
    src: /tmp/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz 
    dest: /opt/
    copy: no

- name: Edit /opt/mattermost/config/config.json
  lineinfile:
    dest: /opt/mattermost/config/config.json
    regexp: '"DriverName": "mysql",'
    line: '        "DriverName": "postgres",'

- name: Edit /opt/mattermost/config/config.json
  lineinfile:
    dest: /opt/mattermost/config/config.json
    regexp: '"DataSource":'
    line: '        "DataSource": "postgres://{{ db_user }}:{{ db_password }}@127.0.0.1:5432/{{ db_name }}?sslmode=disable&connect_timeout=10",'

- name: Create mattermost user
  user: 
    name: "{{ mattermost_user }}"
    system: yes
    createhome: no        

- name: Create mattermost init script
  template:
    src: init_script_ubuntu.j2
    dest: /etc/init.d/mattermost
    owner: root
    group: root
    mode: 0755
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")  

- name: Create mattermost init script
  template:
    src: mattermost.conf.j2
    dest: /etc/init/mattermost.conf
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "6")  

- name: Create mattermost systemd service
  template:
    src: mattermost.service.j2
    dest: /etc/systemd/system/mattermost.service
    owner: root
    group: root
    mode: 0664
  when: (ansible_os_family  == "RedHat" and ansible_distribution_major_version == "7") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16")  

- name: Change mattermost directory permissions
  file:
    path: /opt/mattermost
    state: directory
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_user }}"
    recurse: yes

- name: Enable Mattermost service
  service:
    name: mattermost
    enabled: yes
    state: started
