---
- include: RHEL7.yml
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")   
          
- include: RHEL6.yml
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "6")   
          
- name: Start postgres service
  service:
    name: postgresql-9.4
    state: started

- name: Copy pg_hba.conf to allow password connections from 127.0.0.1
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.4/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600
  when: ansible_os_family == "RedHat"

- name: Restart postgres service
  service:
    name: postgresql-9.4
    state: restarted 

    
