---
- name: Install postgres rpm repo (RHEL 6)
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-6-x86_64/pgdg-redhat94-9.4-2.noarch.rpm
    state: present
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")   
          
- name: Install postgres rpm repo (CentOS 6)
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-2.noarch.rpm
    state: present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")   
