---
- name: Install git
  package:
    name: git
    state: present

- name: git clone letsencrypt/letsencrypt
  git: 
    repo: https://github.com/letsencrypt/letsencrypt 
    dest: /opt/letsencrypt/

- name: Install EPEL repository (CentOS/RHEL 6 only)
  yum:
    name: http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    state: present
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "6")

- name: Enable RHEL 6 Server Optional RPMs (RHEL 6 only)
  command: subscription-manager repos --enable rhel-6-server-optional-rpms
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")

- name: Enable RHEL 7 Server Optional RPMs (RHEL 7 only)
  command: subscription-manager repos --enable rhel-7-server-optional-rpms
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: Install letsencrypt dependencies (takes a while)
  command: /opt/letsencrypt/letsencrypt-auto --help ## This is a bit stupid but it installs the deps without input.

- name: Create letsencrypt config file /opt/letsencrypt/cli.ini
  template: 
    src: cli.ini.j2
    dest: /opt/letsencrypt/cli.ini

- name: Let https through firewall (RHEL 7)
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: Let http through firewall (RHEL 7)
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: Open the correct IPTables ports
  lineinfile: dest=/etc/sysconfig/iptables
              regexp="^-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
              line="-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
              insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
   with_items:
    - { protocol: tcp, port: 80 }
    - { protocol: tcp, port: 443 }
    - { protocol: tcp, port: 22 }
    - { protocol: udp, port: 80 }
    - { protocol: udp, port: 443 }
    - { protocol: udp, port: 22 }
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")

- name: Restart iptables
  service:
    name: iptables
    state: restarted
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")

- name: Allow nginx to connect to MatterMost
  command: setsebool httpd_can_network_connect true

#### MUST REMEMBER TO REMOVE STAGING FLAG ##### (I hit the rate limiter in testing.)
- name: Get SSL certificate from letsencrypt
  command: /opt/letsencrypt/letsencrypt-auto certonly -c /opt/letsencrypt/cli.ini --agree-tos --staging
  args:
    creates: /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem